# Some basic programming exercises on numpy

In [3]:
import numpy as np

#### 1. Create a vector 'int_vector' (1 dimensional array) filled with random 10 integer numbers

In [10]:
# code
int_vector = np.random.randint(low=1, high=10, size=10)
print(int_vector)

[9 6 2 4 3 8 1 6 6 4]


#### 2. Create a vector 'rand_vector' filled with random 10 numbers between 0 and 1

In [13]:
# code
rand_vector = np.random.rand(1,10)
print(rand_vector)

[[ 0.88140871  0.61551008  0.38591032  0.07034841  0.92756227  0.00241562
   0.51234978  0.54404636  0.08581267  0.03408931]]


#### 3. Find the smallest and largest element in int_vector you created in step 1. 
 * Do this with and without using the numpy in-built function. Print the result
 

In [24]:
# code
print(int_vector.min())   
print(int_vector.max()) 

# not built in
min =int_vector[0]
max =int_vector[0];
for i in int_vector:
    val =int_vector[i]
    if(val<min):
        min =val
    elif(i>max):
        max=val
print(min,max)

1
9
(1, 9)


#### 4. Create a vector 'vect1' with 9 elements equally spaced between 10 and 100  

In [26]:
# code
vect1=np.linspace(10,100,9)
print(vect1)

[  10.     21.25   32.5    43.75   55.     66.25   77.5    88.75  100.  ]


#### 5. Create a 4x4 matrix 'mat1' that has 1 in its diagonal entry and 0 else where.

In [29]:
mat1=np.eye(4)
print mat1

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


#### 6. Create a 5x5 matrix 'mat2' that is populated with random numbers between 0 and 1

In [32]:
mat2 = np.random.random((5,5))
print(mat2)

[[ 0.96197225  0.03388988  0.31036285  0.2604476   0.51896165]
 [ 0.52974071  0.2219376   0.23856529  0.79842931  0.36466076]
 [ 0.49238161  0.62643788  0.09835795  0.88602962  0.17545385]
 [ 0.60590267  0.42889239  0.73687399  0.4603339   0.37332588]
 [ 0.85708961  0.19082428  0.78673009  0.8872369   0.33762689]]


#### 7. Save the contents of 'mat2' to a csv file called 'mat2.csv'. 
 * Make sure you preserve 6 values after the decimal point.
 * Next read the contents of the csv file 'mat2.csv' and print its contents on screen

In [36]:
# save with 6 point precision 

np.savetxt('mat2.csv', mat2, delimiter=',', fmt='%.6f')

In [42]:
# read the contents of csv into mat2_data 
mat2_data  = np.genfromtxt('mat2.csv',delimiter=',')

In [43]:
# print the contents. Each item has only 6 values after the decimal point
print(mat2_data )

[[ 0.961972  0.03389   0.310363  0.260448  0.518962]
 [ 0.529741  0.221938  0.238565  0.798429  0.364661]
 [ 0.492382  0.626438  0.098358  0.88603   0.175454]
 [ 0.605903  0.428892  0.736874  0.460334  0.373326]
 [ 0.85709   0.190824  0.78673   0.887237  0.337627]]


#### 8. Define a function 'operation' that takes three input arguments: data1, data2 and operationType
 * Data1 and data2 can be a scalar, vector or matrix.
 * operationType is a string variable that takes one of the following 4 values and performs element-wise operation for
   * add, subtract, multiply, divide
 * The function must return the result of the operation to the caller
   


In [49]:
def operation(data1, data2, operationType):
    """Data1 and data2 can be a scalar, vector or matrix.\
    operationType is a string variable that takes one of the following 4 values \
    and performs element-wise operation for
    add, subtract, multiply, divide"""
    if(operationType =='add'):
        result = data1+data2
    elif(operationType =='subtract'):
         result = data1-data2
    elif(operationType=="multiply"):
        result = data1*data2
    elif(operationType=="divide"):
        result = data1/data2
    else:
        return 
    return result

#### 9. Test the function 'operation' for different operations (say, add, multiply) on following inputs 
 * a)  A 4 element random vector 'rand_v' and the matrix mat1 that was created earlier. Function call will be: operation(rand_v, mat1, 'add') and operation(rand_v, mat1, 'multiply').
 * b) When you call the function as: operation(mat1, mat2, 'add'), where mat1 and mat2 are matrices created earlier. What output do you get ? 
 
 Observe the results obtained. Illustration of broadcasting. 

In [54]:
# code for a)
rand_v = np.random.random((4))
a=operation(rand_v, mat1, 'add')
print a
a=operation(rand_v, mat1, 'multiply')
print a

[[ 1.49265202  0.40324568  0.09499017  0.28215789]
 [ 0.49265202  1.40324568  0.09499017  0.28215789]
 [ 0.49265202  0.40324568  1.09499017  0.28215789]
 [ 0.49265202  0.40324568  0.09499017  1.28215789]]
[[ 0.49265202  0.          0.          0.        ]
 [ 0.          0.40324568  0.          0.        ]
 [ 0.          0.          0.09499017  0.        ]
 [ 0.          0.          0.          0.28215789]]


In [58]:
# code for b)
mat1 = np.arange(0,5)
print(mat1)
b=operation(mat1, mat2, 'add')
print b

[0 1 2 3 4]
[[ 0.96197225  1.03388988  2.31036285  3.2604476   4.51896165]
 [ 0.52974071  1.2219376   2.23856529  3.79842931  4.36466076]
 [ 0.49238161  1.62643788  2.09835795  3.88602962  4.17545385]
 [ 0.60590267  1.42889239  2.73687399  3.4603339   4.37332588]
 [ 0.85708961  1.19082428  2.78673009  3.8872369   4.33762689]]


#### 10. Create a numpy vector comprising of 25 elements randomly drawn from a standard normal distribution. 
 * Next, convert this to a two dimensional 5 x 5 matrix called 'mat5x5' and print the matrix. 


In [61]:
mat5x5=np.random.standard_normal((5,5))

In [62]:
print(mat5x5)

[[-0.8846332  -0.35896814 -0.84966994 -1.16757863  0.16881738]
 [ 0.51735217 -0.06878542 -1.12455174  0.03017642  1.74426364]
 [ 0.45458539  0.80871514  2.16452482 -0.79904598  0.32560954]
 [ 0.05278067 -0.42542203 -1.01686967 -1.72115107 -1.20372828]
 [ 0.3590576  -1.69706858 -0.06598282  0.5417536  -1.04710205]]


#### 11. Save the three matrices mat1, mat2 and mat5x5 as a compressed numpy binary file 'compressed_matrix'
 * Next also read the file 'compressed_matrix' to access individual matrix and print them.
 

In [77]:
# save matrices in compressed form
# temp=np.append(mat1,mat2, axis=0)
# temp=np.append(temp,mat5x5, axis=0)
compressed_matrix=np.savez_compressed('compressed_matrix', mat1=mat1,mat2=mat2,mat5x5=mat5x5)   

In [83]:
# read and print the compressed matrix
load_compressed = np.load('compressed_matrix.npz')
print(load_compressed.files)
load_compressed['mat1']

['mat5x5', 'mat2', 'mat1']


array([0, 1, 2, 3, 4])

#### 11. Compute the following statistics for the matrix mat5x5
 * a) Global mean and mean across each dimension
 * b) Global variance and variance across each dimension
 

In [80]:
# code for a)
mat5x5.mean()

-0.210516847382928

In [84]:
# code for b)
mat5x5.mean()
mat5x5.std()

0.95541052790072079

#### 12. Matrix multiplication 

In order to multiply two matrices, A and B, the number of columns in A must equal the number of rows in B. Thus, if A is an m x n matrix and B is an r x s matrix, n = r.

 * Given A = 3x3 and B = 3x4 matrices both filled with random numbers. 
 * Write a function 'matrix_multiply' that takes A and B as input and perform multiplication without using numpy in-built function 'dot'. Print the result.
 * Test whether your matrix multiplication code worked correctly by comparing the output you get using the inbuilt np.dot() function.
 
#### Hint: 
You will need to use two for loops. First loop controls the row dimension and the innermost control how many items need to be traversed in each row. 


In [106]:
# Code for the function
A=np.random.rand(3,3)
B=np.random.rand(3,4)
print A
print B

[[ 0.90157625  0.71846465  0.80508424]
 [ 0.08527748  0.14397961  0.59589446]
 [ 0.51877632  0.90884106  0.74990486]]
[[ 0.41421521  0.74256965  0.20389288  0.33512239]
 [ 0.39670092  0.9594118   0.85083555  0.16168031]
 [ 0.62161666  0.67408124  0.18648462  0.52923978]]


In [107]:
def matrix_multiply(A,B):
    C=np.zeros((3,4),  dtype=float)
    for i in len(A):
        for j in len(B.T):
            C[i,j]=A[i]*B[j]
    return C

In [108]:
print matrix_multiply(A,B)
# print(np.dot(A, B.T) ,matrix_multiply(A,B))

TypeError: 'int' object is not iterable